{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{section show=$attribute.content.relation_list}
<table>
<th>Object</th><th>Qualifier</th>
{section var=Relations loop=$attribute.content.relation_list sequence=array( bglight, bgdark )}
{section show=$Relations.item.in_trash|not()}
<tr>
<td>
    {content_view_gui view=embed content_object=fetch( content, object, hash( object_id, $Relations.item.contentobject_id ) )}<br />
</td>
<td>
    {$Relations.item.qualifier}
</td>
</tr>
{/section}
{/section}
</table>
{section-else}
{'There are no related objects.'|i18n( 'design/standard/content/datatype' )}
{/section}